config/routes.rb
Etyme::Application.routes.draw do

  resources :messages

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get "payment/index"
  post "payment/processing"

  constraints(Subdomain) do
    match "/invoices/auto_invoicing" => "invoices#auto_invoicing", :as=>:auto_invoicing, :via=>:get
    match "/invoices/clear_invoices" => "invoices#clear_invoices", :as=>:clear_invoices, :via=>:get
    resources :invoices
    resources :receipts

    match "/timesheets/contract" => "timesheets#contract", :as=>:contract_timesheets, :via=>:get
    match "/timesheets/my_timesheets" =>"timesheets#my_timesheets", :as=>:my_timesheets, :via=>:get

    match "/timesheets/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/timesheets/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/timesheets/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get
    #match "/timesheets/:id/invoice" => "timesheets#invoice", :as=>:approved_to_invoiced_timesheet, :via=>:get


    resources :timesheets
    resources :monthly_timesheets, :controller => 'timesheets'
    resources :weekly_timesheets, :controller => 'timesheets'

    match "/documents/detach/:id" => "documents#detach", :as=>:detach_document, :via=>:get
    match "/documents/listings" => "documents#listings", :as=>:listing_document, :via=>:get
    match "/documents/attach" => "documents#attach", :as=>:attach_document, :via=>:post

    resources :documents
    match "commissions/commission_payment" => "commissions#commission_payment", :as=>:commission_payment, :via=>:get
    match "commissions/index" => "commissions#index", :as=>:commissions, :via=>:get
    resources :commissions

    match "/time_entries/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/time_entries/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/time_entries/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get

    match "/time_entries/get_monthly_view" => "time_entries#get_monthly_view", :as=>:get_monthly_view_time_entry, :via=>:get
    match "/time_entries/get_monthly_entry_form" => "time_entries#get_monthly_entry_form", :as=>:get_monthly_entry_form_time_entry, :via=>:get
    match "/time_entries/add_multiple" => "time_entries#add_multiple", :as=>:add_multiple_time_entry, :via=>:post


    resources :time_entries
    resources :billable_periods

    match "/contracts/cancel_contract/:id" =>"contracts#cancel_contract", :as=>:cancel_contract, :via=>:get
    match "/contracts/new_contract" =>"contracts#new_contract", :as=>:new_contract, :via=>:get
    match "/contracts/my" =>"contracts#my_contracts", :as=>:my_contracts, :via=>:get
    match "/contracts/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/contracts/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    match "/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    resources :contracts

    match "/inquiries/pending_to_accepted" => "inquiries#pending_to_accepted", :as=>:pending_to_accepted_inquiry , :via=>:get
    match "/inquiries/accepted_to_pending"=> "inquiries#accepted_to_pending", :as=>:accepted_to_pending_inquiry ,:via=>:get
    match "/inquiries/pending_to_rejected"=> "inquiries#pending_to_rejected", :as=>:pending_to_rejected_inquiry ,:via=>:get
    match "/inquiries/rejected_to_pending"=> "inquiries#rejected_to_pending", :as=>:rejected_to_pending_inquiry ,:via=>:get
    resources :inquiries
    match "/candidates/join" =>"candidates#join", :as=>:candidate_join, :via=>:get

    match "/candidates/register" =>"candidates#register", :as=>:candidate_registration, :via=>:post
    match "/candidates/list" =>"candidates#list", :as=>:candidate_list, :via=>:get


    match "/candidates/login" =>"candidates#login", :as=>:candidate_login, :via=>:get
    match "/candidates/authenticate" =>"candidates#authenticate", :as=>:candidate_authentication, :via=>:post
    match "/candidates/new_candidate_signup" =>"candidates#new_candidate_signup", :as=>:new_candidate_signup, :via=>:get

    resources :candidates
    match "/jobs/my" =>"jobs#my_jobs", :as=>:my_jobs, :via=>:get
    match "/jobs/:id/view" =>"jobs#view", :as=>:view_job, :via=>:get
    match "/jobs/:id/apply" =>"jobs#apply", :as=>:apply_job, :via=>:get
    match "/jobs/:id/applied" =>"jobs#applied", :as=>:applied_job, :via=>:post
    match "/jobs/portal" =>"jobs#portal", :as=>:portal_job, :via=>:get
    match "/jobs/feed" =>"jobs#feed", :as=>:jobs_feed, :via=>:get, :format => 'rss'

    match "jobs/add_candidates" => "jobs#add_candidates", :as =>:add_candidates_to_job, :via=>:post
    match "jobs/:id/set_job_status_to_active" => "jobs#set_job_status_to_active", :as => :set_job_status_to_active, :via => :get
    match "jobs/:id/set_job_status_to_inactive" => "jobs#set_job_status_to_inactive", :as => :set_job_status_to_inactive, :via => :get
    resources :jobs
    

    match "trainings/:id/set_training_status_to_active" => "trainings#set_training_status_to_active", :as => :set_training_status_to_active, :via => :get
    match "trainings/:id/set_training_status_to_inactive" => "trainings#set_training_status_to_inactive", :as => :set_training_status_to_inactive, :via => :get
    match "/trainings/my_trainings" =>"trainings#my_trainings", :as=>:my_trainings, :via=>:get
    match "/trainings/portal" =>"trainings#portal", :as=>:portal_training, :via=>:get
    match "/trainings/:id/view" =>"trainings#view", :as=>:view_training, :via=>:get
    match "/trainings/:id/apply" =>"trainings#apply", :as=>:apply_training, :via=>:get
    match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:get
    # match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:post
    match "trainings/add_candidates" => "trainings#add_candidates", :as =>:add_candidates_to_training, :via=>:post
    match "trainings/accepted_candidates" => "trainings#accepted_candidates", :as =>:accepted_candidates_training, :via=>:get
    match "/trainings/feed" =>"trainings#feed", :as=>:trainings_feed, :via=>:get, :format => 'rss'
    resources :trainings
    match "/ratings/:id.json/" => "ratings#update", :via=>:post
    resources :ratings
    resources :individuals
    resources :comments #, only: [:create,:new,:index]
    resources :service_types
    match "tenants/index" => "tenants#index", :as=>:tenants, :via=>:get
    match "tenants/:id" => "tenants#show", :as=>:tenants_show, :via=>:put
    resources :tenants

    match "/contacts/:id/send_form_for_requesting_update"=>"contacts#send_form_for_requesting_update", :as=>:send_form_for_requesting_update, :via=>:get
    match "/contacts/import/" => "contacts#import", :as=>:import_contacts, :via=>:post
    match "/contacts/search/" => "contacts#search", :as=>:search_contacts, :via=>:get
    match "/contacts/send_form_for_requesting_multiple_update" => "contacts#send_form_for_requesting_multiple_update", :as=>:send_form_for_requesting_multiple_update_contact, :via=>:post
    match "/contacts/:id/get_activity_stream" => "contacts#get_activity_stream", :as=>:get_activity_stream_contacts, :via=>:get
    # match "/contacts/:data" => "contacts#index" , :via=>:post
    get '/contacts/:data' => 'contacts#index'
    post '/contacts/send_email' => "contacts#send_email"

    resources :contacts
    resources :companies

    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "jobs#portal"

    match "/home/search" => "home#search", :as=>:search_everything, :via=>:get
    #match "/users/sign_in" => "users#sign_in", :as=>:user_session, :via=>:post
    match "/users/:id/change_password" =>"users#change_password", :as=>:change_password_user, :via=>:get
    match "/users/:id/update_password" => "users#update_password", :as=>:update_password_user, :via=>:post
    match "/users/change_my_password" =>"users#change_my_password", :as=>:change_my_password_user, :via=>:get
    match "/users/update_my_password" => "users#update_my_password", :as=>:update_my_password_user, :via=>:post
    #devise_for :user
  end

  #match "/" => "payment#index", as: :payment_index
  match "/myaccounts" => "home#accounts", as: :user_accounts, via: :get
  match "/checkname" => "home#checkname", as: :check_name, via: :get

  # root :to => "home#index"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#main"
  match "/home/send_email" => "home#send_email", :as=>:home_send_email, :via=>:post
  devise_for :users, controllers: {registrations: "milia/registrations" }
  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  #   put 'users' => 'devise/registrations#update', :as => 'user_registration'
  # end
  resources :users
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  
  load_and_authorize_resource
  has_scope :starts_with
  has_scope :by_name


  skip_before_filter :authenticate_tenant!, :only => [:portal,:view,:feed]
  skip_load_and_authorize_resource :only => [:portal,:view,:apply,:feed]
  skip_before_filter :authenticate_user, :only => [:portal,:view,:feed]
  def index
    @trainings = apply_scopes(Training).reorder(sort_column + ' '+ sort_direction).page(params[:page])
    respond_to do |format|
      format.html
      format.json { render json: @trainings }
    end
  end

  def my_trainings
    @trainings = apply_scopes(Training).by_candidate(current_user).reorder(sort_column + ' ' + sort_direction).page(params[:page])
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @trainings }
    end
  end

  def portal
    if(Tenant.find_by_subdomain(current_subdomain) != nil)
      set_tenant
      @trainings = Training.published.reorder(sort_column + ' ' + sort_direction).page(params[:page])
    else
     raise ActionController::RoutingError.new('Requested Subdomain Not Found')
    end
    render :layout => 'portal'
  end

  def view
    if(Tenant.find_by_subdomain(current_subdomain) != nil)
      set_tenant
      @training = Training.find(params[:id])
      if user_signed_in?
          @training.inquiries.each do |inquiry|
            if inquiry.individual_id == current_user.individual.id
              @check_applied =1
            else
              next
            end
          end
          render :layout => 'candidate'
      else
        render :layout => 'portal'
      end
    else
      raise ActionController::RoutingError.new('Requested Subdomain Not Found')
    end
  end


  def apply
    @training = Training.find(params[:id])
    @user = current_user
    @inquiry = Inquiry.new(:training_id=>@training.id, :individual_id => @current_user.individual.id)
    render :layout => 'portal'
  end

  def applied
    @user = User.find(current_user[:id])#candidate = User.new(params[:candidate])
    @training = Training.find(params[:id])
    # @inquiry = Inquiry.new(params[:inquiry])
    @user.add_role :trainee, Tenant.find_by_subdomain(current_subdomain)
    @inquiry = Inquiry.create(:training_id=>@training.id, :individual_id=>current_user.individual.id)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to view_training_path(:id => @training.id, :swap => 1), notice: 'Your application has been recieved.' }
        format.json { render json: @inquiry, status: :created, location: @user }
      else
        format.html { render action: "apply", :layout => 'portal' }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_candidates
    params[:ids].each do |one_id|
      inquiry = Inquiry.create(:training_id=>params[:training_id], :individual_id=>one_id)
      if !inquiry.individual.user.has_role? :trainer, current_tenant then
        inquiry.individual.user.add_role :trainee, current_tenant
      end
    end

    redirect_to(:back)
  end

  def accepted_candidates
    @training = Training.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @training }
    end
  end
  
  def show
    @training = Training.find(params[:id])
    t = @training.ratings
    ratrs = []
    t.each do |r|
      ratrs << User.find(r.user_id)
    end
    @rators = ratrs.map(&:username).join("<br />")
    respond_to do |format|
      format.html 
      format.json { render json: @training }
    end
  end

  def new
    @training = Training.new
    @training.inquiries.build
    trainer_list

    respond_to do |format|
      format.html 
      format.json { render json: @training }
    end
  end
  
  def create
    @training = Training.new(params[:training])
    individual_check = params[:training][:inquiries_attributes]["0"][:individual_id]
    respond_to do |format|
      if !individual_check.empty?
        if @training.save
          format.html { redirect_to @training, notice: 'training was successfully created.' }
          format.json { render json: @training, status: :created, location: @training }
        else
          trainer_list
          format.html { render action: "new" }
          format.json { render json: @training.errors, status: :unprocessable_entity }
        end
      else
        @training.errors.add :base, 'No trainer selected'
        trainer_list
          format.html { render action: "new" }
          format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @training = Training.find(params[:id])
    trainer_list
  end

  def update
    @training = Training.find(params[:id])
    individual_check = params[:training][:inquiries_attributes]["0"][:individual_id]
    respond_to do |format|
      if !individual_check.empty?
          if @training.update_attributes(params[:training])
            format.html { redirect_to @training, notice: 'training was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @training.errors, status: :unprocessable_entity }
          end
      else
        @training.errors.add :base, 'No trainer selected'
        trainer_list
        format.html { render action: "edit" }
        format.json { render json: @traininng.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end
  def set_training_status_to_active
    @training = Training.find(params[:id])
    @training.status = 'Activated'
    @training.published = true
    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to trainings_url, notice: 'Training was successfully activated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end
  def set_training_status_to_inactive
    @training = Training.find(params[:id])
    @training.status = 'Deactivated'
    @training.published = false
    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to trainings_url, notice: 'Training was successfully deactivated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end
  def feed
    if(Tenant.find_by_subdomain(current_subdomain) != nil)
      set_tenant
      @trainings = Training.all(:order => "created_at DESC", :limit => 20) 
      respond_to do |format|
         format.rss { render :layout => false }
      end
    else
     raise ActionController::RoutingError.new('Requested Subdomain Not Found')
    end
  end
  
  private
  helper_method :sort_column, :sort_direction, :trainer_list
  def sort_column
    params[:sort] || "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction])? params[:direction]:'asc'
  end
  def trainer_list
    trainers = []
      @individuals = Individual.all
      @individuals.each do |individual|
        if individual.user_id != nil
          if individual.user.has_role? :trainer, current_tenant
            trainers << individual
          end
        else
          next
        end
      end
      @individual = trainers
  end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/accepted_candidates.html.haml
%p#notice= notice
.row
  .span8
    %h2
      = @training.title
    %hr
    .row
      .span4
        %dl.dl-horizontal
          %dt
            Full time:
          %dd
            = @training.full_time
          %dt
            Duration:
          %dd
            = @training.duration
          %dt
            Locaton:
          %dd
            = @training.location
      .span4
        %dl.dl-horizontal
          %dt
            Start date:
          %dd
            = @training.start_date
          %dt
            End date:
          %dd
            = @training.end_date
    %hr
    .row
      .span8
        %legend
          Description
        =simple_format(@training.description)
    %hr
    .row
      .span8
        %h3
          Applications
        / .pull-right
        /   .btn-group
        /     %button{ 'data-toggle'=>"dropdown", 'class'=>"btn  dropdown-toggle"}
        /       %i.icon-user
        /       Add Candidate
        /       %span.caret
        /     %ul.dropdown-menu
        /       %li
        /         = link_to 'New Candidate', new_candidate_path
        /       %li
        /         = link_to 'Existing Candidate', candidate_list_path(:training_id=>@training.id), :remote => true, :id=>'link-to-add-existing-candidate'
        /       %li
        /         = link_to 'Add Trainer', new_candidate_path(:training_id=>@training.id)
        - if @training.inquiries.count == 0 then
          .alert
            No applications for the training yet
        - else
          %table.table.table-striped
            %thead
              %tr
                %th
                  Candidate Name
                %th
                  Applied On
                %th
                  Account Email
                %th
                  CV
                %th
            %tbody
              - @training.inquiries.are_accepted.each do |inquiry|
                - if !inquiry.individual.user.has_role? :trainer, current_tenant
                  %tr
                  %td
                    =link_to inquiry.individual.name, individual_path(id: inquiry.individual.id,tid: @training.id)
                    - if !inquiry.individual.blank?
                      .badge.badge-success#state_colors
                        = inquiry.state

                  %td
                    = time_ago_in_words(inquiry[:updated_at]) + ' ago'
                  %td
                    =inquiry.individual.user.email
                  %td
                    - if inquiry.individual.cv_url then
                      = link_to inquiry.individual.cv_url do
                        %i.icon.icon-arrow-down
                  %td
                    .btn-group
                      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :class=>'btn'}
                        Actions
                        %b.caret
                      %ul.dropdown-menu
                        - if !inquiry.individual.blank? then
                          %li
                            - if inquiry.pending?
                              = link_to pending_to_accepted_inquiry_path(id: inquiry.id), :id =>'accept' do
                                Accept
                              = link_to pending_to_rejected_inquiry_path(id: inquiry.id), :id =>'reject' do
                                Reject
                            - if inquiry.accepted?
                              = link_to accepted_to_pending_inquiry_path(id: inquiry.id), :id =>'unaccept' do
                                UnAccept
                            - if inquiry.rejected?
                              = link_to rejected_to_pending_inquiry_path(id: inquiry.id), :id =>'unreject' do
                                UnReject
                        %li
                          = link_to 'View', inquiry_path(inquiry)
  .span4  
    .pull-right
      = link_to 'Edit', edit_training_path(@training)
      \|
      = link_to 'Back', trainings_path
  .span4
    .pull-left
      %h1 Trainer
      %h4
        - @training.inquiries.each do |inquiry|
          - if inquiry.individual.user.has_role? :trainer, current_tenant
            %ul{style: "list-style:none;"}
              %li
                %h4
                  = link_to inquiry.individual.name, individual_path(id: inquiry.individual.id,tid: @training.id)

// :javascript
//   $(document).on('ajax:success', '#link-to-add-existing-candidate', function(evt, data, status, xhr){
//     bootbox.dialog(xhr.responseText, { "label": "Cancel"});
//     $('.modal-body').css('max-height','750px');
//   });

app/views/trainings/edit.html.haml
%h1 Editing Training

= render 'form'

= link_to 'Show', @training
\|
= link_to 'Back', trainings_path

app/views/trainings/show.html.haml
%p#notice= notice
.row
  .span8
    %h2
      = @training.title
    %hr
    .row
      .span4
        %dl.dl-horizontal
          %dt
            Full time:
          %dd
            = @training.full_time
          %dt
            Duration:
          %dd
            = @training.duration
          %dt
            Locaton:
          %dd
            = @training.location
      .span4
        %dl.dl-horizontal
          %dt
            Start date:
          %dd
            = @training.start_date
          %dt
            End date:
          %dd
            = @training.end_date
          %dt
            Status:
          %dd
            = @training.status
    %hr
    .row
      .span8
        %legend
          Description
        =simple_format(@training.description)

    - if current_user.has_role? :trainee, current_tenant then
      %hr
      .row
        .span3.pull-right
          %h3
            %a#ratorstooltip{"data-placement" => "bottom", "data-toggle" => "tooltip", href: "#", title: "#{@rators}</br>"} Rators List
        .span4
          %h3 Ratings
          .alert-success#success
          #average_rating{style: "display:inline;"}
            = 'Average rating: ' + @training.avg_rating.to_s + ' stars'
        .span8.pull-right
          / %h1 Ratings
          %br
          = current_user.username + ' your rating:'
          - form_id = "training_#{@training.id}_rating"
          - if user_signed_in?
            - user_id = current_user.id
          - else
            - user_id = -1
          = form_for @training.ratings.find_or_create_by_user_id current_user.id do |f|
            = f.hidden_field :training_id, :value => @training.id
            - if user_signed_in?
              = f.hidden_field :user_id, :value => current_user.id
            = f.hidden_field :stars, :id => form_id + "_stars"
          - (1..5).each do |i|
            %li.rating_star{"data-form-id" => form_id, "data-stars" => i, id: "#{form_id}_#{i}"}
    %hr
    .row
      .span8
        %h3
          Applications
        .pull-right
          .btn-group
            %button{ 'data-toggle'=>"dropdown", 'class'=>"btn  dropdown-toggle"}
              %i.icon-user
              Add
              %span.caret
            %ul.dropdown-menu
              %li
                / = link_to 'Add Trainee', "#"
                = link_to 'Add Trainee', new_candidate_path(:training_id=>@training.id)
              / %li
              /   = link_to 'New Candidate', new_candidate_path
              / %li
              /   = link_to 'Existing Candidate', candidate_list_path(:training_id=>@training.id), :remote => true, :id=>'link-to-add-existing-candidate'
              / %li
              /   = link_to 'Add Trainer', new_candidate_path(:training_id=>@training.id)
        - if @training.inquiries.count == 0 then
          .alert
            No applications for the training yet
        - else
          %table.table.table-striped
            %thead
              %tr
                %th
                  Candidate Name
                %th
                  Applied On
                %th
                  Account Email
                %th
                  CV
                %th
            %tbody
              - @training.inquiries.each do |inquiry|
                - if inquiry.individual_id !=nil
                  - if inquiry.individual.user_id != nil
                    - if !inquiry.individual.user.has_role? :trainer, current_tenant
                      %tr
                      %td
                        =link_to inquiry.individual.name, individual_path(id: inquiry.individual.id,tid: @training.id)
                        - if !inquiry.individual.blank?
                          - if inquiry.state == 'accepted'
                            .badge.badge-success
                              = inquiry.state
                          - if inquiry.state == 'rejected'
                            .badge.btn-danger.btn-mini
                              = inquiry.state
                          - if inquiry.state == 'pending'
                            .badge.badge-warning
                              = inquiry.state

                      %td
                        = time_ago_in_words(inquiry[:updated_at]) + ' ago'
                      %td
                        =inquiry.individual.user.email
                      %td
                        - if inquiry.individual.cv_url then
                          = link_to inquiry.individual.cv_url do
                            %i.icon.icon-arrow-down
                      %td
                        .btn-group
                          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :class=>'btn'}
                            Actions
                            %b.caret
                          %ul.dropdown-menu
                            - if !inquiry.individual.blank? 
                              - if current_user.has_role? :admin, current_tenant
                                %li
                                  - if inquiry.pending?
                                    = link_to pending_to_accepted_inquiry_path(id: inquiry.id, tid: @training.id), :id =>'accept' do
                                      Accept
                                    / = link_to pending_to_accepted_inquiry_path(id: inquiry.id), :id =>'accept' do
                                    /   Accept
                                    = link_to pending_to_rejected_inquiry_path(id: inquiry.id, tid: @training.id), :id =>'reject' do
                                      Reject
                                  - if inquiry.accepted?
                                    = link_to accepted_to_pending_inquiry_path(id: inquiry.id, tid: @training.id), :id =>'unaccept' do
                                      UnAccept
                                  - if inquiry.rejected?
                                    = link_to rejected_to_pending_inquiry_path(id: inquiry.id, tid: @training.id), :id =>'unreject' do
                                      UnReject
                            %li
                              = link_to 'View', inquiry_path(inquiry)
    #anchorcomment
    .row
      .span8
        %hr
          %h3 Comment
        - @resource = @training
        = render 'trainings/comments'

  .span4  
    .pull-right
      = link_to 'Edit', edit_training_path(@training)
      \|
      = link_to 'Back', trainings_path
  .span4
    .pull-left
      %h1 Trainer
      %h4
        - @training.inquiries.each do |inquiry|
          - if inquiry.individual_id !=nil
            - if inquiry.individual.user_id != nil
              - if inquiry.individual.user.has_role? :trainer, current_tenant
                %ul{style: "list-style:none;"}
                  %li
                    %h4
                      = link_to inquiry.individual.name, individual_path(id: inquiry.individual.id,tid: @training.id)
    .span4{style: "margin-top:18em;"}
      %hr
        %h3
          %a{href: "#anchorcomment"}
            %img{src: "/assets/comment.jpg"}

:css
  li.rating_star {
  float:left;
  list-style: none;
  margin: 0;
  padding: 0; 
  width: 25px;
  height: 25px;
  background: url(/assets/star.png) top left;
  } 

  li.rating_star.on {
    background: url(/assets/star.png) 0 -25px;
  }

  li.rating_starr {
  float:left;
  list-style: none;
  margin: 0;
  padding: 0; 
  width: 25px;
  height: 25px;
  background: url(/assets/star.png) 0 -25px;
  } 

  // li.rating_starr.on {
  //   background: url(/assets/star.png) 0 -25px;
  // }

:javascript
  $(document).on('ajax:success', '#link-to-add-existing-candidate', function(evt, data, status, xhr){
    bootbox.dialog(xhr.responseText, { "label": "Cancel"});
    $('.modal-body').css('max-height','750px');
  });

  $('.rating_starr').click(function() {
    $('#not_trainee').text('Only a trainee can rate');
  });

  $('#ratorstooltip').tooltip({html: true});