config/routes.rb
Etyme::Application.routes.draw do

  resources :messages

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get "payment/index"
  post "payment/processing"

  constraints(Subdomain) do
    match "/invoices/auto_invoicing" => "invoices#auto_invoicing", :as=>:auto_invoicing, :via=>:get
    match "/invoices/clear_invoices" => "invoices#clear_invoices", :as=>:clear_invoices, :via=>:get
    resources :invoices
    resources :receipts

    match "/timesheets/contract" => "timesheets#contract", :as=>:contract_timesheets, :via=>:get
    match "/timesheets/my_timesheets" =>"timesheets#my_timesheets", :as=>:my_timesheets, :via=>:get

    match "/timesheets/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/timesheets/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/timesheets/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get
    #match "/timesheets/:id/invoice" => "timesheets#invoice", :as=>:approved_to_invoiced_timesheet, :via=>:get


    resources :timesheets
    resources :monthly_timesheets, :controller => 'timesheets'
    resources :weekly_timesheets, :controller => 'timesheets'

    match "/documents/detach/:id" => "documents#detach", :as=>:detach_document, :via=>:get
    match "/documents/listings" => "documents#listings", :as=>:listing_document, :via=>:get
    match "/documents/attach" => "documents#attach", :as=>:attach_document, :via=>:post

    resources :documents
    match "commissions/commission_payment" => "commissions#commission_payment", :as=>:commission_payment, :via=>:get
    match "commissions/index" => "commissions#index", :as=>:commissions, :via=>:get
    resources :commissions

    match "/time_entries/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/time_entries/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/time_entries/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get

    match "/time_entries/get_monthly_view" => "time_entries#get_monthly_view", :as=>:get_monthly_view_time_entry, :via=>:get
    match "/time_entries/get_monthly_entry_form" => "time_entries#get_monthly_entry_form", :as=>:get_monthly_entry_form_time_entry, :via=>:get
    match "/time_entries/add_multiple" => "time_entries#add_multiple", :as=>:add_multiple_time_entry, :via=>:post


    resources :time_entries
    resources :billable_periods

    match "/contracts/cancel_contract/:id" =>"contracts#cancel_contract", :as=>:cancel_contract, :via=>:get
    match "/contracts/new_contract" =>"contracts#new_contract", :as=>:new_contract, :via=>:get
    match "/contracts/my" =>"contracts#my_contracts", :as=>:my_contracts, :via=>:get
    match "/contracts/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/contracts/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    match "/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    resources :contracts

    match "/inquiries/pending_to_accepted" => "inquiries#pending_to_accepted", :as=>:pending_to_accepted_inquiry , :via=>:get
    match "/inquiries/accepted_to_pending"=> "inquiries#accepted_to_pending", :as=>:accepted_to_pending_inquiry ,:via=>:get
    match "/inquiries/pending_to_rejected"=> "inquiries#pending_to_rejected", :as=>:pending_to_rejected_inquiry ,:via=>:get
    match "/inquiries/rejected_to_pending"=> "inquiries#rejected_to_pending", :as=>:rejected_to_pending_inquiry ,:via=>:get
    resources :inquiries
    match "/candidates/join" =>"candidates#join", :as=>:candidate_join, :via=>:get

    match "/candidates/register" =>"candidates#register", :as=>:candidate_registration, :via=>:post
    match "/candidates/list" =>"candidates#list", :as=>:candidate_list, :via=>:get


    match "/candidates/login" =>"candidates#login", :as=>:candidate_login, :via=>:get
    match "/candidates/authenticate" =>"candidates#authenticate", :as=>:candidate_authentication, :via=>:post
    match "/candidates/new_candidate_signup" =>"candidates#new_candidate_signup", :as=>:new_candidate_signup, :via=>:get

    resources :candidates
    match "/jobs/my" =>"jobs#my_jobs", :as=>:my_jobs, :via=>:get
    match "/jobs/:id/view" =>"jobs#view", :as=>:view_job, :via=>:get
    match "/jobs/:id/apply" =>"jobs#apply", :as=>:apply_job, :via=>:get
    match "/jobs/:id/applied" =>"jobs#applied", :as=>:applied_job, :via=>:post
    match "/jobs/portal" =>"jobs#portal", :as=>:portal_job, :via=>:get
    match "/jobs/feed" =>"jobs#feed", :as=>:jobs_feed, :via=>:get, :format => 'rss'

    match "jobs/add_candidates" => "jobs#add_candidates", :as =>:add_candidates_to_job, :via=>:post
    match "jobs/:id/set_job_status_to_active" => "jobs#set_job_status_to_active", :as => :set_job_status_to_active, :via => :get
    match "jobs/:id/set_job_status_to_inactive" => "jobs#set_job_status_to_inactive", :as => :set_job_status_to_inactive, :via => :get
    resources :jobs
    

    match "trainings/:id/set_training_status_to_active" => "trainings#set_training_status_to_active", :as => :set_training_status_to_active, :via => :get
    match "trainings/:id/set_training_status_to_inactive" => "trainings#set_training_status_to_inactive", :as => :set_training_status_to_inactive, :via => :get
    match "/trainings/my_trainings" =>"trainings#my_trainings", :as=>:my_trainings, :via=>:get
    match "/trainings/portal" =>"trainings#portal", :as=>:portal_training, :via=>:get
    match "/trainings/:id/view" =>"trainings#view", :as=>:view_training, :via=>:get
    match "/trainings/:id/apply" =>"trainings#apply", :as=>:apply_training, :via=>:get
    match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:get
    # match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:post
    match "trainings/add_candidates" => "trainings#add_candidates", :as =>:add_candidates_to_training, :via=>:post
    match "trainings/accepted_candidates" => "trainings#accepted_candidates", :as =>:accepted_candidates_training, :via=>:get
    match "/trainings/feed" =>"trainings#feed", :as=>:trainings_feed, :via=>:get, :format => 'rss'
    resources :trainings
    match "/ratings/:id.json/" => "ratings#update", :via=>:post
    resources :ratings
    resources :individuals
    resources :comments #, only: [:create,:new,:index]
    resources :service_types
    match "tenants/index" => "tenants#index", :as=>:tenants, :via=>:get
    match "tenants/:id" => "tenants#show", :as=>:tenants_show, :via=>:put
    resources :tenants

    match "/contacts/:id/send_form_for_requesting_update"=>"contacts#send_form_for_requesting_update", :as=>:send_form_for_requesting_update, :via=>:get
    match "/contacts/import/" => "contacts#import", :as=>:import_contacts, :via=>:post
    match "/contacts/search/" => "contacts#search", :as=>:search_contacts, :via=>:get
    match "/contacts/send_form_for_requesting_multiple_update" => "contacts#send_form_for_requesting_multiple_update", :as=>:send_form_for_requesting_multiple_update_contact, :via=>:post
    match "/contacts/:id/get_activity_stream" => "contacts#get_activity_stream", :as=>:get_activity_stream_contacts, :via=>:get
    # match "/contacts/:data" => "contacts#index" , :via=>:post
    get '/contacts/:data' => 'contacts#index'
    post '/contacts/send_email' => "contacts#send_email"

    resources :contacts
    resources :companies

    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "jobs#portal"

    match "/home/search" => "home#search", :as=>:search_everything, :via=>:get
    #match "/users/sign_in" => "users#sign_in", :as=>:user_session, :via=>:post
    match "/users/:id/change_password" =>"users#change_password", :as=>:change_password_user, :via=>:get
    match "/users/:id/update_password" => "users#update_password", :as=>:update_password_user, :via=>:post
    match "/users/change_my_password" =>"users#change_my_password", :as=>:change_my_password_user, :via=>:get
    match "/users/update_my_password" => "users#update_my_password", :as=>:update_my_password_user, :via=>:post
    #devise_for :user
  end

  #match "/" => "payment#index", as: :payment_index
  match "/myaccounts" => "home#accounts", as: :user_accounts, via: :get
  match "/checkname" => "home#checkname", as: :check_name, via: :get

  # root :to => "home#index"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#main"
  match "/home/send_email" => "home#send_email", :as=>:home_send_email, :via=>:post
  devise_for :users, controllers: {registrations: "milia/registrations" }
  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  #   put 'users' => 'devise/registrations#update', :as => 'user_registration'
  # end
  resources :users
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :desc, :expiry_date, :filename, :filesize, :issue_date, :title, :file, :documentables_attributes
  has_many :documentables
  #serialize :headers, :format=>:yaml
  accepts_nested_attributes_for :documentables
  mount_uploader :file, FileUploader
  acts_as_tenant
  def attach(dType, dId)
    self.documentables.create(:documentable_type => dType, :documentable_id => dId)
  end

  def is_expired?
    !self.expiry_date.blank? && (self.expiry_date < Date.today)
  end

  def close_to_expiry?
    !self.expiry_date.blank? && ((self.expiry_date - Date.today).to_i < 7) && ((self.expiry_date - Date.today).to_i > 0)
  end

  scope :not_by_documentable, lambda{ |documentable| 
  where("`documents`.`id` NOT IN 
      (select `documentables`.`document_id` from `documentables` where `documentables`.`documentable_type`= ? AND `documentables`.`documentable_id` = ?)", 
      documentable.documentable_type, documentable.documentable_id)
  }

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  load_and_authorize_resource
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  def listings
    @documents = Document.not_by_documentable(Documentable.new(:documentable_type=>params[:dType], :documentable_id=>params[:dId]))

    respond_to do |format|
      if request.xhr?
        format.html { render :layout => false}
      else
        format.html # index.html.erb
        format.json { render json: @documents }
      end
    end
  end
  
  def attach
    @documents = Document.find(params[:document_ids])
    @documents.each do |one_document|
      one_document.attach(params[:dType], params[:dId])
    end

    respond_to do |format|
      if request.xhr?
        #format.html { render :layout => false}
        format.js
      else
        format.html # index.html.erb
        format.json { render json: @documents }
      end      
      #format.html { redirect_to :back, notice: 'Service Types Default templates have been set.' }
    end
  end

  def detach
    document = Documentable.find(params[:id])
    document.destroy

    respond_to do |format|
      if request.xhr?
      format.json { head :no_content }
      else
        format.html # index.html.erb
        format.json { render json: @documents }
      end
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    if !params[:dType].blank? then
      @document.documentables.build(:documentable_type => params[:dType], :documentable_id => params[:dId])
    end

    respond_to do |format|
      if request.xhr?
        format.html { render :layout => false}
      else
        format.html # new.html.erb
        format.json { render json: @document }
      end
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    respond_to do |format|
      if request.xhr?
        format.html { render :layout => false}
      else
        format.html # new.html.erb
        format.json { render json: @document }
      end
    end
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        if request.xhr? || remotipart_submitted?
          #format.html{render :layout => false}#, :template => (params[:template] == 'escape' ? 'comments/escape_test' : 'comments/create'), :status => (@comment.errors.any? ? :unprocessable_entity : :ok)
          format.js
        else
          format.html { redirect_to @document, notice: 'Document was successfully created.' }
          format.json { render json: @document, status: :created, location: @document }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        if request.xhr? || remotipart_submitted?
          format.js
        else
          format.html { redirect_to @document, notice: 'Document was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_attachabot.html.haml
.base
  %p
    .pull-left
      %b
        ATTACHED DOCUMENTS 
    .pull-right
      .btn-group
        %button{'data-toggle'=>"dropdown", 'class'=>"btn btn-mini dropdown-toggle"}
          %i.icon-plus-sign
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to new_document_path(:dType=>(resource.class.name), :dId=>resource.id), :remote=>true, :class=>'remote-form-in-bootbox' do
              Upload From Computer

          %li
            = link_to listing_document_path(:dType=>(resource.class.name), :dId=>resource.id), :remote=>true, :class=>'remote-form-in-bootbox' do
              Attach Existing

  %p.clearfix
    %table.table.no-side-margin.no-side-padding
      - resource.documentables.each do |one_documentable|
        %tr
          %td
            = link_to one_documentable.document.file_url do
              = one_documentable.document.title
            - if one_documentable.document.is_expired? then
              .label.label-important{:title=>'Document past expiry date'}
                %i.icon-time.icon-white
            - if one_documentable.document.close_to_expiry? then
              %small.label.label-warning{:title=>'Document expires in a week'}
                %i.icon-time.icon-white
          %td
            .btn-group
              = link_to edit_document_path(one_documentable.document), :remote=>:true,  :class=>'btn btn-mini', :class=>'remote-form-in-bootbox btn btn-mini' do
                %i.icon-pencil
              = link_to detach_document_path(one_documentable), :remote=>:true, :title=>'Detach Document', :class=>'btn btn-mini btn-danger link-to-detach-document' do
                %i.icon-remove.icon-white

:javascript
  $(document).on('ajax:success', '.remote-form-in-bootbox', function(evt, data, status, xhr){
    bootbox.dialog(xhr.responseText, { "label": "Cancel"});
  });

  $(document).on('ajax:success', '.link-to-detach-document', function(evt, data, status, xhr){
    $(this).parents('tr').first().css('backgroundColor', 'red').hide('slow');
  });

app/views/documents/_form.html.haml
= simple_form_for(@document) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :filename
    = f.input :desc
    = f.input :issue_date
    = f.input :expiry_date
    = f.input :filesize
    = f.input :file

  .form-actions
    = f.button :submit

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Title
    %th Filename
    %th Desc
    %th Issue date
    %th Expiry date
    %th Filesize
    %th File
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.title
      %td= document.filename
      %td= document.desc
      %td= document.issue_date
      %td= document.expiry_date
      %td= document.filesize
      %td= document.file
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Document', new_document_path

app/views/documents/listings.html.haml
%h1 Listing documents

%table
  %tr
    %th Title
    %th Filename
    %th Desc
    %th Issue date
    %th Expiry date
    %th Filesize
    %th File
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.title
      %td= document.filename
      %td= document.desc
      %td= document.issue_date
      %td= document.expiry_date
      %td= document.filesize
      %td= document.file
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @document.title
%p
  %b Filename:
  = @document.filename
%p
  %b Desc:
  = @document.desc
%p
  %b Issue date:
  = @document.issue_date
%p
  %b Expiry date:
  = @document.expiry_date
%p
  %b Filesize:
  = @document.filesize
%p
  %b File:
  = @document.file

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path