config/routes.rb
Etyme::Application.routes.draw do

  resources :messages

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get "payment/index"
  post "payment/processing"

  constraints(Subdomain) do
    match "/invoices/auto_invoicing" => "invoices#auto_invoicing", :as=>:auto_invoicing, :via=>:get
    match "/invoices/clear_invoices" => "invoices#clear_invoices", :as=>:clear_invoices, :via=>:get
    resources :invoices
    resources :receipts

    match "/timesheets/contract" => "timesheets#contract", :as=>:contract_timesheets, :via=>:get
    match "/timesheets/my_timesheets" =>"timesheets#my_timesheets", :as=>:my_timesheets, :via=>:get

    match "/timesheets/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/timesheets/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/timesheets/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/timesheets/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get
    #match "/timesheets/:id/invoice" => "timesheets#invoice", :as=>:approved_to_invoiced_timesheet, :via=>:get


    resources :timesheets
    resources :monthly_timesheets, :controller => 'timesheets'
    resources :weekly_timesheets, :controller => 'timesheets'

    match "/documents/detach/:id" => "documents#detach", :as=>:detach_document, :via=>:get
    match "/documents/listings" => "documents#listings", :as=>:listing_document, :via=>:get
    match "/documents/attach" => "documents#attach", :as=>:attach_document, :via=>:post

    resources :documents
    match "commissions/commission_payment" => "commissions#commission_payment", :as=>:commission_payment, :via=>:get
    match "commissions/index" => "commissions#index", :as=>:commissions, :via=>:get
    resources :commissions

    match "/time_entries/:id/unapproved_to_pending" => "timesheets#unapproved_to_pending", :as=>:unapproved_to_pending_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_approved" => "timesheets#pending_to_approved", :as=>:pending_to_approved_timesheet, :via=>:get
    match "/time_entries/:id/approved_to_unapproved" => "timesheets#approved_to_unapproved", :as=>:approved_to_unapproved_timesheet, :via=>:get
    match "/time_entries/:id/pending_to_rejected" => "timesheets#pending_to_rejected", :as=>:pending_to_rejected_timesheet, :via=>:get
    match "/time_entries/:id/rejected_to_unapproved" => "timesheets#rejected_to_unapproved", :as=>:rejected_to_unapproved_timesheet, :via=>:get

    match "/time_entries/get_monthly_view" => "time_entries#get_monthly_view", :as=>:get_monthly_view_time_entry, :via=>:get
    match "/time_entries/get_monthly_entry_form" => "time_entries#get_monthly_entry_form", :as=>:get_monthly_entry_form_time_entry, :via=>:get
    match "/time_entries/add_multiple" => "time_entries#add_multiple", :as=>:add_multiple_time_entry, :via=>:post


    resources :time_entries
    resources :billable_periods

    match "/contracts/cancel_contract/:id" =>"contracts#cancel_contract", :as=>:cancel_contract, :via=>:get
    match "/contracts/new_contract" =>"contracts#new_contract", :as=>:new_contract, :via=>:get
    match "/contracts/my" =>"contracts#my_contracts", :as=>:my_contracts, :via=>:get
    match "/contracts/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/contracts/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    match "/get_candidates/:id" =>"contracts#get_candidates", :as=>:get_candidates, :via=>:get
    match "/get_customer/:id" =>"contracts#get_customer", :as=>:get_customer, :via=>:get
    resources :contracts

    match "/inquiries/pending_to_accepted" => "inquiries#pending_to_accepted", :as=>:pending_to_accepted_inquiry , :via=>:get
    match "/inquiries/accepted_to_pending"=> "inquiries#accepted_to_pending", :as=>:accepted_to_pending_inquiry ,:via=>:get
    match "/inquiries/pending_to_rejected"=> "inquiries#pending_to_rejected", :as=>:pending_to_rejected_inquiry ,:via=>:get
    match "/inquiries/rejected_to_pending"=> "inquiries#rejected_to_pending", :as=>:rejected_to_pending_inquiry ,:via=>:get
    resources :inquiries
    match "/candidates/join" =>"candidates#join", :as=>:candidate_join, :via=>:get

    match "/candidates/register" =>"candidates#register", :as=>:candidate_registration, :via=>:post
    match "/candidates/list" =>"candidates#list", :as=>:candidate_list, :via=>:get


    match "/candidates/login" =>"candidates#login", :as=>:candidate_login, :via=>:get
    match "/candidates/authenticate" =>"candidates#authenticate", :as=>:candidate_authentication, :via=>:post
    match "/candidates/new_candidate_signup" =>"candidates#new_candidate_signup", :as=>:new_candidate_signup, :via=>:get

    resources :candidates
    match "/jobs/my" =>"jobs#my_jobs", :as=>:my_jobs, :via=>:get
    match "/jobs/:id/view" =>"jobs#view", :as=>:view_job, :via=>:get
    match "/jobs/:id/apply" =>"jobs#apply", :as=>:apply_job, :via=>:get
    match "/jobs/:id/applied" =>"jobs#applied", :as=>:applied_job, :via=>:post
    match "/jobs/portal" =>"jobs#portal", :as=>:portal_job, :via=>:get
    match "/jobs/feed" =>"jobs#feed", :as=>:jobs_feed, :via=>:get, :format => 'rss'

    match "jobs/add_candidates" => "jobs#add_candidates", :as =>:add_candidates_to_job, :via=>:post
    match "jobs/:id/set_job_status_to_active" => "jobs#set_job_status_to_active", :as => :set_job_status_to_active, :via => :get
    match "jobs/:id/set_job_status_to_inactive" => "jobs#set_job_status_to_inactive", :as => :set_job_status_to_inactive, :via => :get
    resources :jobs
    

    match "trainings/:id/set_training_status_to_active" => "trainings#set_training_status_to_active", :as => :set_training_status_to_active, :via => :get
    match "trainings/:id/set_training_status_to_inactive" => "trainings#set_training_status_to_inactive", :as => :set_training_status_to_inactive, :via => :get
    match "/trainings/my_trainings" =>"trainings#my_trainings", :as=>:my_trainings, :via=>:get
    match "/trainings/portal" =>"trainings#portal", :as=>:portal_training, :via=>:get
    match "/trainings/:id/view" =>"trainings#view", :as=>:view_training, :via=>:get
    match "/trainings/:id/apply" =>"trainings#apply", :as=>:apply_training, :via=>:get
    match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:get
    # match "/trainings/:id/applied" =>"trainings#applied", :as=>:applied_training, :via=>:post
    match "trainings/add_candidates" => "trainings#add_candidates", :as =>:add_candidates_to_training, :via=>:post
    match "trainings/accepted_candidates" => "trainings#accepted_candidates", :as =>:accepted_candidates_training, :via=>:get
    match "/trainings/feed" =>"trainings#feed", :as=>:trainings_feed, :via=>:get, :format => 'rss'
    resources :trainings
    match "/ratings/:id.json/" => "ratings#update", :via=>:post
    resources :ratings
    resources :individuals
    resources :comments #, only: [:create,:new,:index]
    resources :service_types
    match "tenants/index" => "tenants#index", :as=>:tenants, :via=>:get
    match "tenants/:id" => "tenants#show", :as=>:tenants_show, :via=>:put
    resources :tenants

    match "/contacts/:id/send_form_for_requesting_update"=>"contacts#send_form_for_requesting_update", :as=>:send_form_for_requesting_update, :via=>:get
    match "/contacts/import/" => "contacts#import", :as=>:import_contacts, :via=>:post
    match "/contacts/search/" => "contacts#search", :as=>:search_contacts, :via=>:get
    match "/contacts/send_form_for_requesting_multiple_update" => "contacts#send_form_for_requesting_multiple_update", :as=>:send_form_for_requesting_multiple_update_contact, :via=>:post
    match "/contacts/:id/get_activity_stream" => "contacts#get_activity_stream", :as=>:get_activity_stream_contacts, :via=>:get
    # match "/contacts/:data" => "contacts#index" , :via=>:post
    get '/contacts/:data' => 'contacts#index'
    post '/contacts/send_email' => "contacts#send_email"

    resources :contacts
    resources :companies

    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "jobs#portal"

    match "/home/search" => "home#search", :as=>:search_everything, :via=>:get
    #match "/users/sign_in" => "users#sign_in", :as=>:user_session, :via=>:post
    match "/users/:id/change_password" =>"users#change_password", :as=>:change_password_user, :via=>:get
    match "/users/:id/update_password" => "users#update_password", :as=>:update_password_user, :via=>:post
    match "/users/change_my_password" =>"users#change_my_password", :as=>:change_my_password_user, :via=>:get
    match "/users/update_my_password" => "users#update_my_password", :as=>:update_my_password_user, :via=>:post
    #devise_for :user
  end

  #match "/" => "payment#index", as: :payment_index
  match "/myaccounts" => "home#accounts", as: :user_accounts, via: :get
  match "/checkname" => "home#checkname", as: :check_name, via: :get

  # root :to => "home#index"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#main"
  match "/home/send_email" => "home#send_email", :as=>:home_send_email, :via=>:post
  devise_for :users, controllers: {registrations: "milia/registrations" }
  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  #   put 'users' => 'devise/registrations#update', :as => 'user_registration'
  # end
  resources :users
end

app/models/company.rb
class Company < Contact
  acts_as_citier
  acts_as_tenant
  acts_as_commentable
  #attr_accessor :company_name, :description, :timezone, :website, :twenty_four_ops, :type, :company_type
  #attr_accessor :contact_details_attributes, :phone_attributes, :fax_attributes, :email_attributes, :im_attributes
  #attr_accessor :address_detail_attributes, :typeb_attributes, :aftn_attributes, :addresses_attributes, :radio_attributes, :icao_attributes
  attr_accessible :company_name, :description, :timezone, :website, :twenty_four_ops, :type, :company_type
  attr_accessible :contact_details_attributes, :phone_attributes, :fax_attributes, :email_attributes, :im_attributes
  attr_accessible :address_detail_attributes, :addresses_attributes
  attr_accessible :phone, :fax, :email
  attr_accessible :tags_as_text, :tag_list
  attr_taggable :tags

  #liquid_methods :company_name, :addresses
  
  #virtual attributes
  def tag_list=(tag_list)
    @tag_list = tag_list
    self.tags = @tag_list.split(',')
  end

  def tag_list
    @tag_list
  end

  def tags_as_text=(tags_as_text)
    @tags_as_text = tags_as_text
  end

  def tags_as_text
    @tags_as_text
  end

  def has_individuals?
    self.individuals.count>0
  end

  def num_individuals
    self.individuals.count
  end

  before_save :set_parent_attributes, :reset_null_to_empty
  #associations

  has_many :individuals
  has_many :jobs, :dependent => :destroy


  validates_presence_of :company_name, :description, :company_type
  validates_uniqueness_of :company_name, :scope => :tenant_id

  
  def reset_null_to_empty
    if self[:description] == nil then
      self[:description] = ""
    end
  end

  def set_parent_attributes
    self[:name] = self[:company_name]
    self[:about] = self[:description]
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  load_and_authorize_resource

  def index
    @companies = apply_scopes(Company).all
    @tenant = current_tenant
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    #raise @company.contact_details.inspect
    #@history = @company.audits + @company.associated_audits

    respond_to do |format|
      format.html #{render :layout=>'no-margins'} show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_contact_detail_fields.html.haml
= f.input :contact_type, :as=>:hidden, :input_html{:value=>'phone'}
= f.input :location
= f.input :details

app/views/companies/_form.html.haml
= simple_form_for(@company, :html=>{:class=>' form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :company_name, :input_html=>{:class=>'input-xxlarge'}
    = f.input :website
    = f.input :twenty_four_ops, :wrapper_html=>{:class=>'check-width'}
    = f.input :timezone, :as=>:time_zone
    = f.input :company_type, :collection => ['Vendor', 'Client'], :required => true
    %legend
      Tags
    %p
      Enter Tags seperated by commas
    = f.input :tags_as_text, :style=>'float:left;', :class=>'input-small'
    = f.input :tag_list, :as=>:hidden
    %legend
      Contact Information
    .control-group
      %label.control-label
        Phone
      = f.fields_for(:phone) do|builder|
        - render 'contact_details/phone_fields', :f => builder
          
      .controls
        = link_to_add_contact_detail_fields "Add a phone", f, :phone
    .control-group
      %label.control-label
        Fax
      = f.fields_for(:fax) do|builder|
        - render 'contact_details/fax_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add a fax", f, :fax
    .control-group
      %label.control-label
        Email
      = f.fields_for(:email) do|builder|
        - render 'contact_details/email_fields', :f => builder

      .controls
        = link_to_add_contact_detail_fields "Add an Email Address", f, :email
    .control-group
      %label.control-label
        Internet Messenger
      = f.fields_for(:im) do|builder|
        - render 'contact_details/im_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add Internet Messenger", f, :im

    .control-group
      %label.control-label
        Address
      = f.fields_for(:addresses) do|builder|
        - render 'contact_details/address_fields', :f => builder
      .controls
        = link_to_add_address_detail_fields "Add Address", f, :addresses
    %legend
      Services
    .control-group
      = f.association :service_types, :collection=>ServiceType.all.map { |r| [r.desc, r.id] }, :input_html=>{:class=>'input-xxlarge', :style=>'height:350px;'}
    %hr
    = f.input :description, :input_html=>{:class=>'input-xxlarge', :rows=>6}, :required => true

  .form-actions
    = f.button :submit

    
:javascript
  
  tags_source = document.getElementById('company_tag_list').value.split(',');

  jQuery('#company_tags_as_text').tagsManager({ hiddenTagListName: 'company[tag_list]',hiddenTagListId: 'company_tag_list', prefilled:tags_source, typeahead: true, preventSubmitOnEnter: true });

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Company name
    %th Description
    %th
    %th
    %th

  - @companies.each do |company|
    %tr
      %td= company.company_name
      %td= company.description
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h3 Add A Company

= render 'form'

app/views/companies/show.html.haml
- content_for(:title) do
  - "Company::"+@company.company_name 

.row
  .span8
    %h3
      =@company.company_name
    #profile
      - @resource = @company
      = #render 'layouts/generic_comments_audits'

  .span4
    .well
      = link_to 'Edit', edit_company_path(@company), :class=>'btn'
      = link_to 'Back', companies_path, :class=>'btn'
    - @contact = @company
    = render :partial=>'contact_details/contact_details', :local=>{:contact=>@company}
    
    - if !@company.description.blank? then
      %hr
      %p
        %b 
          ='About '+@company.company_name.to_s
      = @company.description
    / - if @company.service_types.count > 0
    /   %hr
    /   %p
    /     %b
    /       Services Offered
    /       %small
    /         (Company Specific Template)
    /     - @company.contacts_service_types.each do |one_contact_service|
    /       %div
    /         = one_contact_service.service_type[:desc]
    /         %small
    /           (
    /           = best_in_place one_contact_service, :template_id, :display_as=>:template_name, :type => :select, :collection => ::Template.all.map { |r| [r.id,r.title] },  :ok_button=>'OK', :cancel_button=>'Cancel'
    /           )
    - if @company.individuals.count > 0
      %hr
      %p
        %b
          People who work here
      %table.table
        - @company.individuals.each do |one_individual|
          %tr
            %td
              = link_to one_individual[:salutation].to_s + ' ' + one_individual.name.to_s, one_individual
              %br
              %small
                =one_individual[:designation]


:javascript
 
  var timer = $.timer(function() {
    $.ajax({
      url: "/contacts/#{@company[:id]}/get_activity_stream",
    }).done(function (html) {
      $('#history').html(html);
    });
  });

  timer.set({ time : 10000, autostart : true });

  $('.best_in_place').best_in_place();